name: green_sense
description: Every green seed of awareness grows a brighter future


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  url_strategy: ^0.2.0
  scroll_to_index: ^3.0.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  web:
    generate: true
    image_path: "images/logo.png"
    background_color: "#F7FCF7FF"
    theme_color: "#ffffff"

flutter_app_name:
  name: "Green Sense"